### ISSUE TITLE
error about searching, add playlist and button not work due to application not respond

### ISSUE THREAD

**Issue by tofut777** [jumpers775/Tempo#11]
2024-07-01 02:52:19 INFO     discord.voice_state Connecting to voice...
2024-07-01 02:52:19 INFO     discord.voice_state Starting voice handshake... (connection attempt 1)
2024-07-01 02:52:20 INFO     discord.voice_state Voice handshake complete. Endpoint found: hongkong11019.discord.media
2024-07-01 02:52:20 INFO     discord.voice_state Voice connection complete.
{"asd": []}
2024-07-01 03:16:18 ERROR    discord.app_commands.tree Ignoring exception in command 'add'
Traceback (most recent call last):
  File "C:\Users\tofut\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\app_commands\commands.py", line 858, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tofut\Desktop\DisBot\Tempo2\bot.py", line 966, in add
    title = results[i]['title'][:80]
            ~~~~~~~^^^
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tofut\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\app_commands\tree.py", line 1310, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\tofut\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\app_commands\commands.py", line 883, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tofut\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\app_commands\commands.py", line 876, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'add' raised an exception: IndexError: list index out of range
{"asd": []}
2024-07-01 03:16:35 ERROR    discord.app_commands.tree Ignoring exception in command 'add'
Traceback (most recent call last):
  File "C:\Users\tofut\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\app_commands\commands.py", line 858, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tofut\Desktop\DisBot\Tempo2\bot.py", line 966, in add
    title = results[i]['title'][:80]
            ~~~~~~~^^^
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tofut\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\app_commands\tree.py", line 1310, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\tofut\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\app_commands\commands.py", line 883, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tofut\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\app_commands\commands.py", line 876, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'add' raised an exception: IndexError: list index out of range
{}

**Comment by lucamignatti** [comment]
sorry about this. i will be putting out a V2 within the next month or so that will not have this issue. In the meantime if i get a chance i will try and put out a bugfix for the 1.x.x line.
