### ISSUE TITLE
espeak not installed

### ISSUE THREAD

**Issue by jasong500** [jumpers775/Tempo#13]
So I'm on windows and  just tried setting up this bot for the first time today and when I follow the instructions provided I get an error that espeak is not installed. I've tried going and installing espeak manually and closing and reopening the powershell window (running it as admin just to make sure there's no issues) and i still get this same error.

```
(base) PS D:\MusicBot\Tempo> conda activate Tempo
(Tempo) PS D:\MusicBot\Tempo> python .\bot.py
Traceback (most recent call last):
  File "D:\MusicBot\Tempo\bot.py", line 4, in <module>
    import libTempo
  File "D:\MusicBot\Tempo\libTempo.py", line 9, in <module>
    from tts import generate
  File "D:\MusicBot\Tempo\tts.py", line 17, in <module>
    from matcha.text import sequence_to_text, text_to_sequence
  File "C:\Users\jason\miniconda3\envs\Tempo\Lib\site-packages\matcha\text\__init__.py", line 2, in <module>
    from matcha.text import cleaners
  File "C:\Users\jason\miniconda3\envs\Tempo\Lib\site-packages\matcha\text\cleaners.py", line 27, in <module>
    global_phonemizer = phonemizer.backend.EspeakBackend(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason\miniconda3\envs\Tempo\Lib\site-packages\phonemizer\backend\espeak\espeak.py", line 45, in __init__
    super().__init__(
  File "C:\Users\jason\miniconda3\envs\Tempo\Lib\site-packages\phonemizer\backend\espeak\base.py", line 39, in __init__
    super().__init__(
  File "C:\Users\jason\miniconda3\envs\Tempo\Lib\site-packages\phonemizer\backend\base.py", line 77, in __init__
    raise RuntimeError(  # pragma: nocover
RuntimeError: espeak not installed on your system
```

**Comment by lucamignatti** [comment]
I think [this issue](https://github.com/bootphon/phonemizer/issues/44#issuecomment-634175018) should fix it. Please let me know if it does so i can add it to the setup documentation.

**Comment by jasong500** [comment]
That did indeed fix the issue. Appreciate the support! You should probably consider making the espeak component and the speech to text stuff an optional install though.

**Comment by lucamignatti** [comment]
Glad to hear it's fixed! I would like to make it optional, however it's required by a dependency of a dependency I use in the (currently disabled) voice mode.
