### ISSUE TITLE
Issue on play from yt

### ISSUE THREAD

**Issue by Fernando6909** [jumpers775/Tempo#9]
[2024-05-11 17:51:09] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'play'
Traceback (most recent call last):
  File "C:\Users\Fernando\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\app_commands\commands.py", line 828, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Fernando\Documents\Tempo-1.2.1\bot.py", line 451, in play
    if not spot:
           ^^^^
UnboundLocalError: cannot access local variable 'spot' where it is not associated with a value

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Fernando\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\Fernando\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Fernando\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'play' raised an exception: UnboundLocalError: cannot access local variable 'spot' where it is not associated with a value

I believe I followed the correct step-by-step, any help is welcome

**Comment by lucamignatti** [comment]
Try restarting the bot.


I'm pretty busy, so it may take a few more days before I can fix this.

**Comment by lucamignatti** [comment]
sorry, github automatically closed this. I *think* it should be fixed, but please let me know if it really is.

**Comment by lucamignatti** [comment]
closing due to inactivity. I believe this is fixed.
